apiVersion: v1
kind: ReplicationController
metadata:
  name: myreplica
spec:
  replicas: 3
  selector:
    app: myapp
  template:
    metadata:
      name: testpod
      labels:
        app: myapp
    spec:
      containers:
        - name: C001
          image: httpd
          ports:
            - containerPort: 80
